# App Name
spring.application.name=SavaariPK-Backend

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost\\MSSQLSERVER01;databaseName=SavaariPK_DB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Savaari123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Server Port
server.port=8080